<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>update</AssemblyName>
    <RootNamespace>TerminalSimulation.Updater</RootNamespace>
    <DebugType>embedded</DebugType>
    <Version>2.0.0</Version>
  </PropertyGroup>
</Project>
