param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

$mapKey = if ($env:CTS_TENCENT_MAP_KEY) {
    $env:CTS_TENCENT_MAP_KEY.Trim()
} elseif (Test-Path -LiteralPath $InputPath) {
    (Get-Content -LiteralPath $InputPath -Raw).Trim()
} else {
    ''
}

if ([string]::IsNullOrWhiteSpace($mapKey)) {
    throw "Tencent Maps key is missing. Create $InputPath or set CTS_TENCENT_MAP_KEY."
}

$utf8 = [System.Text.Encoding]::UTF8
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$wrappingKey = $sha256.ComputeHash($utf8.GetBytes('CTS.Preview9.TencentMap.Key.Wrap.v1'))
$aes = [System.Security.Cryptography.Aes]::Create()
$aes.Key = $wrappingKey
$aes.Mode = [System.Security.Cryptography.CipherMode]::CBC
$aes.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7
$aes.GenerateIV()

try {
    $plainBytes = $utf8.GetBytes($mapKey)
    $encryptor = $aes.CreateEncryptor()
    $cipherBytes = $encryptor.TransformFinalBlock($plainBytes, 0, $plainBytes.Length)
    $ivLiteral = ($aes.IV | ForEach-Object { $_.ToString() }) -join ', '
    $cipherLiteral = ($cipherBytes | ForEach-Object { $_.ToString() }) -join ', '
    $source = @(
        '// <auto-generated/>',
        'namespace TerminalSimulation.Wpf.Services;',
        '',
        'internal static class EmbeddedTencentMapCredential',
        '{',
        ('    internal static readonly byte[] InitializationVector = [{0}];' -f $ivLiteral),
        ('    internal static readonly byte[] CipherText = [{0}];' -f $cipherLiteral),
        '}',
        ''
    ) -join [Environment]::NewLine

    $outputDirectory = Split-Path -Parent $OutputPath
    [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
    [System.IO.File]::WriteAllText($OutputPath, $source, [System.Text.UTF8Encoding]::new($false))
}
finally {
    if ($plainBytes) { [Array]::Clear($plainBytes, 0, $plainBytes.Length) }
    [Array]::Clear($wrappingKey, 0, $wrappingKey.Length)
    $aes.Dispose()
    $sha256.Dispose()
}
